// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: queuer/entities/v1/status.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on HardwareStats with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *HardwareStats) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HardwareStats with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in HardwareStatsMultiError, or
// nil if none found.
func (m *HardwareStats) ValidateAll() error {
	return m.validate(true)
}

func (m *HardwareStats) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TotalCpu

	// no validation rules for FreeCpu

	// no validation rules for TotalRam

	// no validation rules for FreeRam

	if len(errors) > 0 {
		return HardwareStatsMultiError(errors)
	}

	return nil
}

// HardwareStatsMultiError is an error wrapping multiple validation errors
// returned by HardwareStats.ValidateAll() if the designated constraints
// aren't met.
type HardwareStatsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HardwareStatsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HardwareStatsMultiError) AllErrors() []error { return m }

// HardwareStatsValidationError is the validation error returned by
// HardwareStats.Validate if the designated constraints aren't met.
type HardwareStatsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HardwareStatsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HardwareStatsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HardwareStatsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HardwareStatsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HardwareStatsValidationError) ErrorName() string { return "HardwareStatsValidationError" }

// Error satisfies the builtin error interface
func (e HardwareStatsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHardwareStats.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HardwareStatsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HardwareStatsValidationError{}

// Validate checks the field values on NetworkStats with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NetworkStats) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NetworkStats with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NetworkStatsMultiError, or
// nil if none found.
func (m *NetworkStats) ValidateAll() error {
	return m.validate(true)
}

func (m *NetworkStats) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Ip

	// no validation rules for Speed

	if len(errors) > 0 {
		return NetworkStatsMultiError(errors)
	}

	return nil
}

// NetworkStatsMultiError is an error wrapping multiple validation errors
// returned by NetworkStats.ValidateAll() if the designated constraints aren't met.
type NetworkStatsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NetworkStatsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NetworkStatsMultiError) AllErrors() []error { return m }

// NetworkStatsValidationError is the validation error returned by
// NetworkStats.Validate if the designated constraints aren't met.
type NetworkStatsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NetworkStatsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NetworkStatsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NetworkStatsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NetworkStatsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NetworkStatsValidationError) ErrorName() string { return "NetworkStatsValidationError" }

// Error satisfies the builtin error interface
func (e NetworkStatsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNetworkStats.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NetworkStatsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NetworkStatsValidationError{}

// Validate checks the field values on Stats with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Stats) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Stats with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in StatsMultiError, or nil if none found.
func (m *Stats) ValidateAll() error {
	return m.validate(true)
}

func (m *Stats) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetStats()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, StatsValidationError{
					field:  "Stats",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, StatsValidationError{
					field:  "Stats",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStats()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StatsValidationError{
				field:  "Stats",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetNetwork()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, StatsValidationError{
					field:  "Network",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, StatsValidationError{
					field:  "Network",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNetwork()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StatsValidationError{
				field:  "Network",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return StatsMultiError(errors)
	}

	return nil
}

// StatsMultiError is an error wrapping multiple validation errors returned by
// Stats.ValidateAll() if the designated constraints aren't met.
type StatsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StatsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StatsMultiError) AllErrors() []error { return m }

// StatsValidationError is the validation error returned by Stats.Validate if
// the designated constraints aren't met.
type StatsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StatsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StatsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StatsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StatsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StatsValidationError) ErrorName() string { return "StatsValidationError" }

// Error satisfies the builtin error interface
func (e StatsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStats.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StatsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StatsValidationError{}
