// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: queuer/consumers/v1/presence.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on IAmAliveRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *IAmAliveRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IAmAliveRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IAmAliveRequestMultiError, or nil if none found.
func (m *IAmAliveRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *IAmAliveRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTimestamp()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IAmAliveRequestValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IAmAliveRequestValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTimestamp()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IAmAliveRequestValidationError{
				field:  "Timestamp",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return IAmAliveRequestMultiError(errors)
	}

	return nil
}

// IAmAliveRequestMultiError is an error wrapping multiple validation errors
// returned by IAmAliveRequest.ValidateAll() if the designated constraints
// aren't met.
type IAmAliveRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IAmAliveRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IAmAliveRequestMultiError) AllErrors() []error { return m }

// IAmAliveRequestValidationError is the validation error returned by
// IAmAliveRequest.Validate if the designated constraints aren't met.
type IAmAliveRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IAmAliveRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IAmAliveRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IAmAliveRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IAmAliveRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IAmAliveRequestValidationError) ErrorName() string { return "IAmAliveRequestValidationError" }

// Error satisfies the builtin error interface
func (e IAmAliveRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIAmAliveRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IAmAliveRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IAmAliveRequestValidationError{}

// Validate checks the field values on IAmAliveResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *IAmAliveResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IAmAliveResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IAmAliveResponseMultiError, or nil if none found.
func (m *IAmAliveResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *IAmAliveResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTimestamp()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IAmAliveResponseValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IAmAliveResponseValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTimestamp()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IAmAliveResponseValidationError{
				field:  "Timestamp",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return IAmAliveResponseMultiError(errors)
	}

	return nil
}

// IAmAliveResponseMultiError is an error wrapping multiple validation errors
// returned by IAmAliveResponse.ValidateAll() if the designated constraints
// aren't met.
type IAmAliveResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IAmAliveResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IAmAliveResponseMultiError) AllErrors() []error { return m }

// IAmAliveResponseValidationError is the validation error returned by
// IAmAliveResponse.Validate if the designated constraints aren't met.
type IAmAliveResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IAmAliveResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IAmAliveResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IAmAliveResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IAmAliveResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IAmAliveResponseValidationError) ErrorName() string { return "IAmAliveResponseValidationError" }

// Error satisfies the builtin error interface
func (e IAmAliveResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIAmAliveResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IAmAliveResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IAmAliveResponseValidationError{}
