// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: queuer/consumers/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ConsumerService_PublishConsumerStats_FullMethodName = "/queuer.consumers.v1.ConsumerService/PublishConsumerStats"
	ConsumerService_GetSubscribedStreams_FullMethodName = "/queuer.consumers.v1.ConsumerService/GetSubscribedStreams"
)

// ConsumerServiceClient is the client API for ConsumerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsumerServiceClient interface {
	PublishConsumerStats(ctx context.Context, opts ...grpc.CallOption) (ConsumerService_PublishConsumerStatsClient, error)
	GetSubscribedStreams(ctx context.Context, in *GetSubscribedStreamsRequest, opts ...grpc.CallOption) (*GetSubscribedStreamsResponse, error)
}

type consumerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsumerServiceClient(cc grpc.ClientConnInterface) ConsumerServiceClient {
	return &consumerServiceClient{cc}
}

func (c *consumerServiceClient) PublishConsumerStats(ctx context.Context, opts ...grpc.CallOption) (ConsumerService_PublishConsumerStatsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ConsumerService_ServiceDesc.Streams[0], ConsumerService_PublishConsumerStats_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &consumerServicePublishConsumerStatsClient{stream}
	return x, nil
}

type ConsumerService_PublishConsumerStatsClient interface {
	Send(*PublishConsumerStatsRequest) error
	CloseAndRecv() (*PublishConsumerStatsResponse, error)
	grpc.ClientStream
}

type consumerServicePublishConsumerStatsClient struct {
	grpc.ClientStream
}

func (x *consumerServicePublishConsumerStatsClient) Send(m *PublishConsumerStatsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *consumerServicePublishConsumerStatsClient) CloseAndRecv() (*PublishConsumerStatsResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PublishConsumerStatsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *consumerServiceClient) GetSubscribedStreams(ctx context.Context, in *GetSubscribedStreamsRequest, opts ...grpc.CallOption) (*GetSubscribedStreamsResponse, error) {
	out := new(GetSubscribedStreamsResponse)
	err := c.cc.Invoke(ctx, ConsumerService_GetSubscribedStreams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsumerServiceServer is the server API for ConsumerService service.
// All implementations must embed UnimplementedConsumerServiceServer
// for forward compatibility
type ConsumerServiceServer interface {
	PublishConsumerStats(ConsumerService_PublishConsumerStatsServer) error
	GetSubscribedStreams(context.Context, *GetSubscribedStreamsRequest) (*GetSubscribedStreamsResponse, error)
	mustEmbedUnimplementedConsumerServiceServer()
}

// UnimplementedConsumerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedConsumerServiceServer struct {
}

func (UnimplementedConsumerServiceServer) PublishConsumerStats(ConsumerService_PublishConsumerStatsServer) error {
	return status.Errorf(codes.Unimplemented, "method PublishConsumerStats not implemented")
}
func (UnimplementedConsumerServiceServer) GetSubscribedStreams(context.Context, *GetSubscribedStreamsRequest) (*GetSubscribedStreamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscribedStreams not implemented")
}
func (UnimplementedConsumerServiceServer) mustEmbedUnimplementedConsumerServiceServer() {}

// UnsafeConsumerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsumerServiceServer will
// result in compilation errors.
type UnsafeConsumerServiceServer interface {
	mustEmbedUnimplementedConsumerServiceServer()
}

func RegisterConsumerServiceServer(s grpc.ServiceRegistrar, srv ConsumerServiceServer) {
	s.RegisterService(&ConsumerService_ServiceDesc, srv)
}

func _ConsumerService_PublishConsumerStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConsumerServiceServer).PublishConsumerStats(&consumerServicePublishConsumerStatsServer{stream})
}

type ConsumerService_PublishConsumerStatsServer interface {
	SendAndClose(*PublishConsumerStatsResponse) error
	Recv() (*PublishConsumerStatsRequest, error)
	grpc.ServerStream
}

type consumerServicePublishConsumerStatsServer struct {
	grpc.ServerStream
}

func (x *consumerServicePublishConsumerStatsServer) SendAndClose(m *PublishConsumerStatsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *consumerServicePublishConsumerStatsServer) Recv() (*PublishConsumerStatsRequest, error) {
	m := new(PublishConsumerStatsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ConsumerService_GetSubscribedStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscribedStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServiceServer).GetSubscribedStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsumerService_GetSubscribedStreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServiceServer).GetSubscribedStreams(ctx, req.(*GetSubscribedStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsumerService_ServiceDesc is the grpc.ServiceDesc for ConsumerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsumerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "queuer.consumers.v1.ConsumerService",
	HandlerType: (*ConsumerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSubscribedStreams",
			Handler:    _ConsumerService_GetSubscribedStreams_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PublishConsumerStats",
			Handler:       _ConsumerService_PublishConsumerStats_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "queuer/consumers/v1/service.proto",
}
